// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AccessConnect.Models;

public partial class ComprobantesDePago
{
    public int IdDeComprobante { get; set; }

    public int? IdDeUsuarioQueRealizaElPago { get; set; }

    public byte[] ImagenDelComprobante { get; set; }

    public DateTime? FechaDeEnvioDelComprobante { get; set; }

    public string EstadoDeValidacion { get; set; }

    public DateTime? FechaDeValidacion { get; set; }

    public string DetallesDelPago { get; set; }

    public int? IdDeUsuarioDeLaMesaDirectivaQueValidaElPago { get; set; }

    public string Observaciones { get; set; }

    public virtual Usuario IdDeUsuarioDeLaMesaDirectivaQueValidaElPagoNavigation { get; set; }

    public virtual Usuario IdDeUsuarioQueRealizaElPagoNavigation { get; set; }
}