// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AccessConnect.Models;

public partial class Comunicado
{
    public int IdDeComunicado { get; set; }

    public int? IdDeAdministradorQueGeneraElComunicado { get; set; }

    public DateTime? FechaYHoraDeCreacionDelComunicado { get; set; }

    public string TituloDelComunicado { get; set; }

    public string ContenidoDelComunicado { get; set; }

    public string TipoDeComunicado { get; set; }

    public string EstadoDelComunicado { get; set; }

    public virtual Usuario IdDeAdministradorQueGeneraElComunicadoNavigation { get; set; }
}