// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AccessConnect.Models;

public partial class EstadoDeCuentum
{
    public int IdDeEstadoDeCuenta { get; set; }

    public int? IdDeUsuario { get; set; }

    public decimal? SaldoActual { get; set; }

    public string DetallesDePagos { get; set; }

    public string DetallesDeRecargos { get; set; }

    public string DetallesDeAnticipos { get; set; }

    public DateTime? FechaDeGeneracionDelEstadoDeCuenta { get; set; }

    public virtual Usuario IdDeUsuarioNavigation { get; set; }
}