// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AccessConnect.Models;

public partial class Evento
{
    public int IdDeEvento { get; set; }

    public string NombreDelEvento { get; set; }

    public string DescripcionDelEvento { get; set; }

    public DateTime? FechaYHoraDelEvento { get; set; }

    public int? IdDeUsuarioAnfitrion { get; set; }

    public string ClaveUnicaDelEvento { get; set; }

    public DateTime? FechaDeCreacionDelEvento { get; set; }

    public virtual Usuario IdDeUsuarioAnfitrionNavigation { get; set; }

    public virtual ICollection<Invitacione> Invitaciones { get; set; } = new List<Invitacione>();
}