// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AccessConnect.Models;

public partial class Incidente
{
    public int IdDeIncidente { get; set; }

    public int? IdDeUsuarioQueReportaElIncidente { get; set; }

    public string DescripcionDelIncidente { get; set; }

    public string EstadoDelIncidente { get; set; }

    public DateTime? FechaDeReporteDelIncidente { get; set; }

    public string DetallesDeLaMejoraPropuesta { get; set; }

    public DateTime? FechaDeAtencionDelIncidente { get; set; }

    public int? IdDeUsuarioDeLaMesaDirectivaQueAtiendeElIncidente { get; set; }

    public virtual Usuario IdDeUsuarioDeLaMesaDirectivaQueAtiendeElIncidenteNavigation { get; set; }

    public virtual Usuario IdDeUsuarioQueReportaElIncidenteNavigation { get; set; }
}