// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AccessConnect.Models;

public partial class Invitacione
{
    public int IdDeInvitacion { get; set; }

    public int? IdDeEvento { get; set; }

    public int? IdDeInvitado { get; set; }

    public string ClaveUnica { get; set; }

    public DateTime? FechaDeCreacionDeLaInvitacion { get; set; }

    public string EstadoDeLaInvitacion { get; set; }

    public virtual Evento IdDeEventoNavigation { get; set; }

    public virtual Invitado IdDeInvitadoNavigation { get; set; }
}