// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AccessConnect.Models;

public partial class ListaNegraDeVehiculo
{
    public int IdDelVehiculo { get; set; }

    public string PlacaDelVehiculo { get; set; }

    public string DescripcionDelVehiculo { get; set; }

    public string EstadoDelVehiculo { get; set; }
}