// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AccessConnect.Models;

public partial class Mantenimiento
{
    public int IdDeMantenimiento { get; set; }

    public string TipoDeMantenimiento { get; set; }

    public string DescripcionDelMantenimiento { get; set; }

    public DateTime? FechaYHoraProgramadasDelMantenimiento { get; set; }

    public string EstadoDelMantenimiento { get; set; }

    public DateTime? FechaYHoraDeRealizacionDelMantenimiento { get; set; }

    public string DescripcionDeLasAccionesRealizadas { get; set; }

    public int? IdDeResidenteAsociado { get; set; }

    public virtual Usuario IdDeResidenteAsociadoNavigation { get; set; }
}