// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AccessConnect.Models;

public partial class MensajesDelChatConCasetum
{
    public int IdDelMensaje { get; set; }

    public int? IdDeResidenteQueEnviaElMensaje { get; set; }

    public int? IdDeVigilanciaQueRecibeElMensaje { get; set; }

    public string ContenidoDelMensaje { get; set; }

    public DateTime? FechaYHoraDeEnvioDelMensaje { get; set; }

    public string EstadoDelMensaje { get; set; }

    public virtual Usuario IdDeResidenteQueEnviaElMensajeNavigation { get; set; }

    public virtual Usuario IdDeVigilanciaQueRecibeElMensajeNavigation { get; set; }
}