// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AccessConnect.Models;

public partial class MensajesDeEmergencium
{
    public int IdDelMensaje { get; set; }

    public int? IdDeResidenteQueEnviaElMensaje { get; set; }

    public string ContenidoDelMensaje { get; set; }

    public string UbicacionPrecisaDelResidenteAlEnviarElMensaje { get; set; }

    public DateTime? FechaYHoraDeEnvioDelMensaje { get; set; }

    public string EstadoDelMensaje { get; set; }

    public virtual Usuario IdDeResidenteQueEnviaElMensajeNavigation { get; set; }
}