// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AccessConnect.Models;

public partial class OpcionesDeRespuestum
{
    public int IdDeOpcion { get; set; }

    public int? IdDeEncuestaAsociada { get; set; }

    public string TextoDeLaOpcion { get; set; }

    public virtual Encuesta IdDeEncuestaAsociadaNavigation { get; set; }

    public virtual ICollection<RegistroDeVoto> RegistroDeVotos { get; set; } = new List<RegistroDeVoto>();
}