// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AccessConnect.Models;

public partial class Pago
{
    public int IdDePago { get; set; }

    public int? IdDeUsuarioQueRealizaElPago { get; set; }

    public decimal? MontoDelPago { get; set; }

    public DateTime? FechaDePago { get; set; }

    public string EstadoDelPago { get; set; }

    public string MetodoDePago { get; set; }

    public virtual Usuario IdDeUsuarioQueRealizaElPagoNavigation { get; set; }
}