// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AccessConnect.Models;

public partial class Publicacione
{
    public int IdDePublicacion { get; set; }

    public int? IdDeUsuarioQueLaPublica { get; set; }

    public string ContenidoDeLaPublicacion { get; set; }

    public DateTime? FechaDePublicacion { get; set; }

    public string TipoDePublicacion { get; set; }

    public string NivelDeModeracion { get; set; }

    public string EstadoDeLaPublicacion { get; set; }

    public virtual ICollection<Comentario> Comentarios { get; set; } = new List<Comentario>();

    public virtual Usuario IdDeUsuarioQueLaPublicaNavigation { get; set; }
}