// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AccessConnect.Models;

public partial class Reglamento
{
    public int IdDeDocumento { get; set; }

    public string TituloDelDocumento { get; set; }

    public string DescripcionDelDocumento { get; set; }

    public string TipoDeDocumento { get; set; }

    public byte[] ArchivoDelDocumento { get; set; }

    public DateTime? FechaYHoraDeCargaDelDocumento { get; set; }

    public string EstadoDelDocumento { get; set; }
}