// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AccessConnect.Models;

public partial class ReservasDeAmenidade
{
    public int IdDeReserva { get; set; }

    public int? IdDeUsuarioQueRealizaLaReserva { get; set; }

    public int? IdDeAmenidadReservada { get; set; }

    public DateTime? FechaYHoraDeLaReserva { get; set; }

    public string EstadoDeLaReserva { get; set; }

    public DateTime? FechaYHoraDeAprobacionDeLaReserva { get; set; }

    public string DetallesAdicionalesDeLaReserva { get; set; }

    public virtual Amenidade IdDeAmenidadReservadaNavigation { get; set; }

    public virtual Usuario IdDeUsuarioQueRealizaLaReservaNavigation { get; set; }
}