// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AccessConnect.Models;

public partial class ServiciosProgramado
{
    public int IdDeServicio { get; set; }

    public string TipoDeServicio { get; set; }

    public string DescripcionDelServicio { get; set; }

    public DateTime? FechaYHoraProgramadasParaElServicio { get; set; }

    public string EstadoDelServicio { get; set; }

    public int? IdDeResidenteAsociado { get; set; }

    public virtual Usuario IdDeResidenteAsociadoNavigation { get; set; }
}