// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AccessConnect.Models;

public partial class Transaccione
{
    public int IdDeTransaccion { get; set; }

    public int? IdDeUsuarioQueRealizaLaTransaccion { get; set; }

    public string TipoDeTransaccion { get; set; }

    public decimal? MontoDeLaTransaccion { get; set; }

    public DateTime? FechaDeLaTransaccion { get; set; }

    public string DescripcionDeLaTransaccion { get; set; }

    public string Estado { get; set; }

    public virtual Usuario IdDeUsuarioQueRealizaLaTransaccionNavigation { get; set; }
}