// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AccessConnect.Models;

public partial class UsuariosDomicilio
{
    public int IdDeRelacion { get; set; }

    public int? IdDeUsuario { get; set; }

    public int? IdDeDomicilio { get; set; }

    public DateTime? FechaDeAsociacion { get; set; }

    public virtual Domicilio IdDeDomicilioNavigation { get; set; }

    public virtual Usuario IdDeUsuarioNavigation { get; set; }
}