// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AccessConnect.Models;

public partial class Usuario
{
    public int IdDeUsuario { get; set; }

    public string Nombre { get; set; }

    public string Apellido { get; set; }

    public string CorreoElectronico { get; set; }

    public string Contrasena { get; set; }

    public string Rol { get; set; }

    public DateTime? FechaDeCreacion { get; set; }

    public DateTime? UltimaFechaDeInicioDeSesion { get; set; }

    public virtual ICollection<Comentario> Comentarios { get; set; } = new List<Comentario>();

    public virtual ICollection<ComprobantesDePago> ComprobantesDePagoIdDeUsuarioDeLaMesaDirectivaQueValidaElPagoNavigations { get; set; } = new List<ComprobantesDePago>();

    public virtual ICollection<ComprobantesDePago> ComprobantesDePagoIdDeUsuarioQueRealizaElPagoNavigations { get; set; } = new List<ComprobantesDePago>();

    public virtual ICollection<Comunicado> Comunicados { get; set; } = new List<Comunicado>();

    public virtual ICollection<EstadoDeCuentum> EstadoDeCuenta { get; set; } = new List<EstadoDeCuentum>();

    public virtual ICollection<Evento> Eventos { get; set; } = new List<Evento>();

    public virtual ICollection<Incidente> IncidenteIdDeUsuarioDeLaMesaDirectivaQueAtiendeElIncidenteNavigations { get; set; } = new List<Incidente>();

    public virtual ICollection<Incidente> IncidenteIdDeUsuarioQueReportaElIncidenteNavigations { get; set; } = new List<Incidente>();

    public virtual ICollection<Invitado> Invitados { get; set; } = new List<Invitado>();

    public virtual ICollection<Mantenimiento> Mantenimientos { get; set; } = new List<Mantenimiento>();

    public virtual ICollection<Mascota> Mascota { get; set; } = new List<Mascota>();

    public virtual ICollection<MensajesDeEmergencium> MensajesDeEmergencia { get; set; } = new List<MensajesDeEmergencium>();

    public virtual ICollection<MensajesDelChatConCasetum> MensajesDelChatConCasetumIdDeResidenteQueEnviaElMensajeNavigations { get; set; } = new List<MensajesDelChatConCasetum>();

    public virtual ICollection<MensajesDelChatConCasetum> MensajesDelChatConCasetumIdDeVigilanciaQueRecibeElMensajeNavigations { get; set; } = new List<MensajesDelChatConCasetum>();

    public virtual ICollection<Pago> Pagos { get; set; } = new List<Pago>();

    public virtual ICollection<Publicacione> Publicaciones { get; set; } = new List<Publicacione>();

    public virtual ICollection<RecorridosDeSeguridad> RecorridosDeSeguridads { get; set; } = new List<RecorridosDeSeguridad>();

    public virtual ICollection<RegistroDeVoto> RegistroDeVotos { get; set; } = new List<RegistroDeVoto>();

    public virtual ICollection<ReservasDeAmenidade> ReservasDeAmenidades { get; set; } = new List<ReservasDeAmenidade>();

    public virtual ICollection<ServiciosProgramado> ServiciosProgramados { get; set; } = new List<ServiciosProgramado>();

    public virtual ICollection<Transaccione> Transacciones { get; set; } = new List<Transaccione>();

    public virtual ICollection<UsuariosDomicilio> UsuariosDomicilios { get; set; } = new List<UsuariosDomicilio>();
}